# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

import os
import buildconfig

def main(output, *args):
    token = os.environ.get("AXIOM_TOKEN") or os.environ.get("AXIOM_API_KEY")

    if not token:
        try:
            env_path = os.path.join(buildconfig.topsrcdir, ".env")
            if os.path.exists(env_path):
                with open(env_path, "r") as f:
                    for line in f:
                        line = line.strip()
                        if not line or line.startswith("#"):
                            continue
                        parts = line.split("=")
                        if len(parts) >= 2:
                            key = parts[0].strip()
                            value = "=".join(parts[1:]).strip()
                            if (value.startswith('"') and value.endswith('"')) or \
                               (value.startswith("'") and value.endsWith("'")):
                                value = value[1:-1]
                            if key in ("AXIOM_TOKEN", "AXIOM_API_KEY"):
                                token = value
                                break
        except Exception:
            pass

    if not token:
        token = ""

    content = f"""/* Generated by generate_telemetry_config.py during build. Do not edit. */
export var TelemetryConfig = {{
  token: "{token}",
}};
"""
    output.write(content)
