# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

import os
import buildconfig


def main(output, *args):
    token = os.environ.get("AXIOM_TOKEN") or os.environ.get("AXIOM_API_KEY")
    url = os.environ.get("AXIOM_URL") or os.environ.get("AXIOM_ENDPOINT")

    try:
        env_path = os.path.join(buildconfig.topsrcdir, ".env")
        if os.path.exists(env_path):
            with open(env_path, "r") as f:
                for line in f:
                    line = line.strip()
                    if not line or line.startswith("#"):
                        continue
                    parts = line.split("=")
                    if len(parts) >= 2:
                        key = parts[0].strip()
                        value = "=".join(parts[1:]).strip()
                        if (value.startswith('"') and value.endswith('"')) or (
                            value.startswith("'") and value.endsWith("'")
                        ):
                            value = value[1:-1]
                        if key in ("AXIOM_TOKEN", "AXIOM_API_KEY") and not token:
                            token = value
                        elif key in ("AXIOM_URL", "AXIOM_ENDPOINT") and not url:
                            url = value
    except Exception:
        pass

    if not token:
        token = ""
    if not url:
        url = "https://api.axiom.co/v1/datasets/lykon-crashes/ingest"

    content = f"""/* Generated by generate_telemetry_config.py during build. Do not edit. */
export var TelemetryConfig = {{
  token: "{token}",
  url: "{url}",
  async sendReport(eventData) {{
    if (!this.token) {{
      return false;
    }}
    try {{
      let response = await fetch(
        this.url,
        {{
          method: "POST",
          headers: {{
            "Content-Type": "application/json",
            Authorization: "Bearer " + this.token,
          }},
          body: JSON.stringify([eventData]),
        }}
      );
      return response.ok;
    }} catch (e) {{
      console.error(e);
      return false;
    }}
  }}
}};
"""
    output.write(content)
